### ISSUE TITLE
playlist import fails

### ISSUE THREAD

**Issue by iljarogoff** [rern/RuneAudio-Re4#24]
hi, was trying to import a m3u playlist stored in /var/lib/mpd/playlists
this is what i get as result:

![grafik](https://user-images.githubusercontent.com/21023840/88832381-07f3a700-d1d1-11ea-87c8-555e76ac5bb6.png)

thought it is the wrong path to file, so used the direct path to the files and got this

![grafik](https://user-images.githubusercontent.com/21023840/88832709-7df80e00-d1d1-11ea-967b-0713c1824632.png)

where is the mistake?

**Comment by rern** [comment]
Your playlist contains back slashes. The addon was revised to get them converted to forward slashed.
Update RuneAudio+R e4 and try again.
